# -*- coding: utf-8 -*-
"""e3_matias_vergara_S7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xb-Et1X4-bZLaiwjbNY-v22-AfuAoTz0
"""

import numpy as np
matriz = np.random.randint(0,7,[3,3])
print("Juguemos un juego.\nIngresa números a una matriz 3x3, donde su sumatoria sea 21.\n")
for i in range(3):
  for j in range(3):
    z = input(f"Ingresa un numero para la posicion [{i},{j}]:\t")
    matriz[i,j] = z
print("\n",matriz,"\n")
print("La sumatoria de la matriz que creaste es:\t",matriz.sum())
while matriz.sum() != 21:
  print("Los números que has ingresado a la matriz no suman 21, intentalo nuevamente.\n")
  for i in range(3):
    for j in range(3):
      z = input(f"Ingresa un numero para la posicion [{i},{j}]:\t")
      matriz[i,j] = z
  print("\n",matriz,"\n")
  print("La sumatoria de la matriz que creaste es:\t",matriz.sum())
print("Lo lograste, bien hecho. :D")